### ISSUE TITLE
too large number error

### ISSUE THREAD

**Issue by pinq-** [bjarnekvae/pymobitec-flipdot#1]
Hi,
I got your code to work with the text, thanks for that!
But I can't get function "set_pixels" to work.  I have bigger screen ( 24 x 160) and I have updated  the pymobitec_flipdot.py file to match with my screen:

`    # Display width
    header.append(0xd0)
    header.append(160)
    # Display height
    header.append(0xd1)
    header.append(24)
`

`
def set_pixels(pixels):
    pix_map = np.zeros([160, 24], dtype=np.bool)
    pix_map[pixels] = True

    mask = np.bitwise_or(pix_map, set_pixels.display_state)
    set_pixels.display_state = pix_map.copy()

    msg = get_header()
    lines = [40, 80, 120, 160]
    for line in lines:
        # Vertical offset:
        msg.append(0xd3)
        msg.append(line-1)

        # Bitmap Font
        msg.append(0xd4)
        msg.append(0x77)

        horisontal_skip = True
        for horisontal in range(160):
            if mask[horisontal, line-40:line].any():
                # Horizontal offset:
                if horisontal_skip:
                    msg.append(0xd2)
                    msg.append(horisontal)
                    horisontal_skip = False

                bit_array = pix_map[horisontal, line-40:line]

                val = sum(bit_array[i] << i for i in range(len(bit_array)))
                val = val | 0x20

                msg.append(val)
            else:
                horisontal_skip = True

    msg = add_trailer(msg)
    return msg`

But I get an error  "val number is to big" and when I print val number it is something line 162222452. Did I updated somehow wrong way?

**Comment by bjarnekvae** [comment]
Hi pinq!

First of all thanks for using my code! And sorry for the quality ;)

For me et seems that you did everything right, except one thing:

The "lines" array defines the coordinate for the "set pixel"-font (0x77), and I would guess that this font size is the same for all old school Mobitec flip-dot displays, so please try this:


```
def set_pixels(pixels):
    pix_map = np.zeros([160, 24], dtype=np.bool)
    pix_map[pixels] = True

    mask = np.bitwise_or(pix_map, set_pixels.display_state)
    set_pixels.display_state = pix_map.copy()

    msg = get_header()
    lines = [5, 10, 15, 20]
    for line in lines:
        # Vertical offset:
        msg.append(0xd3)
        msg.append(line-1)

        # Bitmap Font
        msg.append(0xd4)
        msg.append(0x77)

        horisontal_skip = True
        for horisontal in range(160):
            if mask[horisontal, line-5:line].any():
                # Horizontal offset:
                if horisontal_skip:
                    msg.append(0xd2)
                    msg.append(horisontal)
                    horisontal_skip = False

                bit_array = pix_map[horisontal, line-5:line]

                val = sum(bit_array[i] << i for i in range(len(bit_array)))
                val = val | 0x20

                msg.append(val)
            else:
                horisontal_skip = True

    msg = add_trailer(msg)
    return msg
```

Also remember to set the correct size for the static varibale:
`set_pixels.display_state = np.zeros([160, 24], dtype=np.bool)`
