### ISSUE TITLE
Install requirements

### ISSUE THREAD

**Issue by bossGovernor2000** [bjarnekvae/pymobitec-flipdot#3]
When trying to run the requirements -install, I get the following error:

`root@DietPi:~/pymobitec-flipdot# pip install requirements
DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/pymobitec_flipdot-0.1-py3.11.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple/
ERROR: Could not find a version that satisfies the requirement requirements (from versions: none)
ERROR: No matching distribution found for requirements
`

**Comment by bjarnekvae** [comment]
Hi there!

Seems like `pip install requirements` is deprecated, see below for new installation instructions. I've also updated the README file.

1. `git clone https://github.com/bjarnekvae/pymobitec-flipdot.git`
2. `cd pymobitec-flipdot`
3. `pip install -r requirements.txt`
4. `python setup.py install`
